feat(replay): add combine player
netless-io/vue-whiteboard pull request #2
Opened 2020-10-29 10:14 UTC by BlackHole1

2020-10-29 10:17 UTC, hyrious approved these changes

2020-11-05 08:09 UTC, hyrious requested changes

2020-11-05 08:09 UTC, hyrious commented on whiteboard/src/views/ReplayPage/components/ReplayPage.vue
> +          return await whiteWebSdk.isPlayable({
should `throw` to trigger `polly()`'s retry
```js
const isPlayable = await ...;
if (!isPlayable) throw "whatever";
return true;
```

2020-11-05 08:25 UTC, BlackHole1 commented on whiteboard/src/views/ReplayPage/components/ReplayPage.vue
> +          return await whiteWebSdk.isPlayable({
fixed: https://github.com/netless-io/vue-whiteboard/pull/2/commits/cdfbbbe01cddda3bd7db706b7bc7ad171ca5a5fa

2020-11-05 08:59 UTC, hyrious approved these changes

2020-11-05 08:59 UTC, merged